name: Build Sample

on:
  pull_request: null
  push:
    branches:
    - main

jobs:
  build:
    name: Build Sample on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        ghc: ["9.2.2"]

    steps:
    - uses: actions/checkout@v2

    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v2.1.7
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/package.yaml') }}-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-stack-
    - uses: haskell/actions/setup@v1.2.9
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: 'latest'

    - name: Install dependencies
      run: stack --docker build --only-dependencies
    - name: Build binary
      run: stack --docker --local-bin-path=./bin install --ghc-options '-optl-static -fPIC -optc-Os'
    - name: Build image
      run: |
        docker build -t sample-image . --build-arg local_bin_path=./bin -f Dockerfile
        docker run --rm sample-image --version
